<?php
return array(
	0   => array(
		'ihg'      => 'Africa',
		'city'     => 'Abidjan',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	1   => array(
		'ihg'      => 'Africa',
		'city'     => 'Accra',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	2   => array(
		'ihg'      => 'Africa',
		'city'     => 'Addis_Ababa',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	3   => array(
		'ihg'      => 'Africa',
		'city'     => 'Algiers',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	4   => array(
		'ihg'      => 'Africa',
		'city'     => 'Asmara',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	5   => array(
		'ihg'      => 'Africa',
		'city'     => 'Bamako',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	6   => array(
		'ihg'      => 'Africa',
		'city'     => 'Bangui',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	7   => array(
		'ihg'      => 'Africa',
		'city'     => 'Banjul',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	8   => array(
		'ihg'      => 'Africa',
		'city'     => 'Bissau',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	9   => array(
		'ihg'      => 'Africa',
		'city'     => 'Blantyre',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	10  => array(
		'ihg'      => 'Africa',
		'city'     => 'Brazzaville',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	11  => array(
		'ihg'      => 'Africa',
		'city'     => 'Bujumbura',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	12  => array(
		'ihg'      => 'Africa',
		'city'     => 'Cairo',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	13  => array(
		'ihg'      => 'Africa',
		'city'     => 'Casablanca',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	14  => array(
		'ihg'      => 'Africa',
		'city'     => 'Ceuta',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	15  => array(
		'ihg'      => 'Africa',
		'city'     => 'Conakry',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	16  => array(
		'ihg'      => 'Africa',
		'city'     => 'Dakar',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	17  => array(
		'ihg'      => 'Africa',
		'city'     => 'Dar_es_Salaam',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	18  => array(
		'ihg'      => 'Africa',
		'city'     => 'Djibouti',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	19  => array(
		'ihg'      => 'Africa',
		'city'     => 'Douala',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	20  => array(
		'ihg'      => 'Africa',
		'city'     => 'El_Aaiun',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	21  => array(
		'ihg'      => 'Africa',
		'city'     => 'Freetown',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	22  => array(
		'ihg'      => 'Africa',
		'city'     => 'Gaborone',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	23  => array(
		'ihg'      => 'Africa',
		'city'     => 'Harare',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	24  => array(
		'ihg'      => 'Africa',
		'city'     => 'Johannesburg',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	25  => array(
		'ihg'      => 'Africa',
		'city'     => 'Juba',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	26  => array(
		'ihg'      => 'Africa',
		'city'     => 'Kampala',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	27  => array(
		'ihg'      => 'Africa',
		'city'     => 'Khartoum',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	28  => array(
		'ihg'      => 'Africa',
		'city'     => 'Kigali',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	29  => array(
		'ihg'      => 'Africa',
		'city'     => 'Kinshasa',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	30  => array(
		'ihg'      => 'Africa',
		'city'     => 'Lagos',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	31  => array(
		'ihg'      => 'Africa',
		'city'     => 'Libreville',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	32  => array(
		'ihg'      => 'Africa',
		'city'     => 'Lome',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	33  => array(
		'ihg'      => 'Africa',
		'city'     => 'Luanda',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	34  => array(
		'ihg'      => 'Africa',
		'city'     => 'Lubumbashi',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	35  => array(
		'ihg'      => 'Africa',
		'city'     => 'Lusaka',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	36  => array(
		'ihg'      => 'Africa',
		'city'     => 'Malabo',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	37  => array(
		'ihg'      => 'Africa',
		'city'     => 'Maputo',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	38  => array(
		'ihg'      => 'Africa',
		'city'     => 'Maseru',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	39  => array(
		'ihg'      => 'Africa',
		'city'     => 'Mbabane',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	40  => array(
		'ihg'      => 'Africa',
		'city'     => 'Mogadishu',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	41  => array(
		'ihg'      => 'Africa',
		'city'     => 'Monrovia',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	42  => array(
		'ihg'      => 'Africa',
		'city'     => 'Nairobi',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	43  => array(
		'ihg'      => 'Africa',
		'city'     => 'Ndjamena',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	44  => array(
		'ihg'      => 'Africa',
		'city'     => 'Niamey',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	45  => array(
		'ihg'      => 'Africa',
		'city'     => 'Nouakchott',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	46  => array(
		'ihg'      => 'Africa',
		'city'     => 'Ouagadougou',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	47  => array(
		'ihg'      => 'Africa',
		'city'     => 'Porto-Novo',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	48  => array(
		'ihg'      => 'Africa',
		'city'     => 'Sao_Tome',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	49  => array(
		'ihg'      => 'Africa',
		'city'     => 'Timbuktu',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	50  => array(
		'ihg'      => 'Africa',
		'city'     => 'Tripoli',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	51  => array(
		'ihg'      => 'Africa',
		'city'     => 'Tunis',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	52  => array(
		'ihg'      => 'Africa',
		'city'     => 'Windhoek',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	53  => array(
		'ihg'      => 'America',
		'city'     => 'Adak',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	54  => array(
		'ihg'      => 'America',
		'city'     => 'Anchorage',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	55  => array(
		'ihg'      => 'America',
		'city'     => 'Anguilla',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	56  => array(
		'ihg'      => 'America',
		'city'     => 'Antigua',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	57  => array(
		'ihg'      => 'America',
		'city'     => 'Araguaina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	58  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	59  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	60  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	61  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	62  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	63  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	64  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	65  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	66  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	67  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	68  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	69  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	70  => array(
		'ihg'      => 'America',
		'city'     => 'Argentina',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	71  => array(
		'ihg'      => 'America',
		'city'     => 'Aruba',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	72  => array(
		'ihg'      => 'America',
		'city'     => 'Asuncion',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	73  => array(
		'ihg'      => 'America',
		'city'     => 'Atikokan',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	74  => array(
		'ihg'      => 'America',
		'city'     => 'Atka',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	75  => array(
		'ihg'      => 'America',
		'city'     => 'Bahia',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	76  => array(
		'ihg'      => 'America',
		'city'     => 'Bahia_Banderas',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	77  => array(
		'ihg'      => 'America',
		'city'     => 'Barbados',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	78  => array(
		'ihg'      => 'America',
		'city'     => 'Belem',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	79  => array(
		'ihg'      => 'America',
		'city'     => 'Belize',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	80  => array(
		'ihg'      => 'America',
		'city'     => 'Blanc-Sablon',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	81  => array(
		'ihg'      => 'America',
		'city'     => 'Boa_Vista',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	82  => array(
		'ihg'      => 'America',
		'city'     => 'Bogota',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	83  => array(
		'ihg'      => 'America',
		'city'     => 'Boise',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	84  => array(
		'ihg'      => 'America',
		'city'     => 'Buenos_Aires',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	85  => array(
		'ihg'      => 'America',
		'city'     => 'Cambridge_Bay',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	86  => array(
		'ihg'      => 'America',
		'city'     => 'Campo_Grande',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	87  => array(
		'ihg'      => 'America',
		'city'     => 'Cancun',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	88  => array(
		'ihg'      => 'America',
		'city'     => 'Caracas',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	89  => array(
		'ihg'      => 'America',
		'city'     => 'Catamarca',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	90  => array(
		'ihg'      => 'America',
		'city'     => 'Cayenne',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	91  => array(
		'ihg'      => 'America',
		'city'     => 'Cayman',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	92  => array(
		'ihg'      => 'America',
		'city'     => 'Chicago',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	93  => array(
		'ihg'      => 'America',
		'city'     => 'Chihuahua',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	94  => array(
		'ihg'      => 'America',
		'city'     => 'Coral_Harbour',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	95  => array(
		'ihg'      => 'America',
		'city'     => 'Cordoba',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	96  => array(
		'ihg'      => 'America',
		'city'     => 'Costa_Rica',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	97  => array(
		'ihg'      => 'America',
		'city'     => 'Creston',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	98  => array(
		'ihg'      => 'America',
		'city'     => 'Cuiaba',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	99  => array(
		'ihg'      => 'America',
		'city'     => 'Curacao',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	100 => array(
		'ihg'      => 'America',
		'city'     => 'Danmarkshavn',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	101 => array(
		'ihg'      => 'America',
		'city'     => 'Dawson',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	102 => array(
		'ihg'      => 'America',
		'city'     => 'Dawson_Creek',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	103 => array(
		'ihg'      => 'America',
		'city'     => 'Denver',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	104 => array(
		'ihg'      => 'America',
		'city'     => 'Detroit',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	105 => array(
		'ihg'      => 'America',
		'city'     => 'Dominica',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	106 => array(
		'ihg'      => 'America',
		'city'     => 'Edmonton',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	107 => array(
		'ihg'      => 'America',
		'city'     => 'Eirunepe',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	108 => array(
		'ihg'      => 'America',
		'city'     => 'El_Salvador',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	109 => array(
		'ihg'      => 'America',
		'city'     => 'Ensenada',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	110 => array(
		'ihg'      => 'America',
		'city'     => 'Fort_Nelson',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	111 => array(
		'ihg'      => 'America',
		'city'     => 'Fort_Wayne',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	112 => array(
		'ihg'      => 'America',
		'city'     => 'Fortaleza',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	113 => array(
		'ihg'      => 'America',
		'city'     => 'Glace_Bay',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	114 => array(
		'ihg'      => 'America',
		'city'     => 'Godthab',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	115 => array(
		'ihg'      => 'America',
		'city'     => 'Goose_Bay',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	116 => array(
		'ihg'      => 'America',
		'city'     => 'Grand_Turk',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	117 => array(
		'ihg'      => 'America',
		'city'     => 'Grenada',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	118 => array(
		'ihg'      => 'America',
		'city'     => 'Guadeloupe',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	119 => array(
		'ihg'      => 'America',
		'city'     => 'Guatemala',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	120 => array(
		'ihg'      => 'America',
		'city'     => 'Guayaquil',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	121 => array(
		'ihg'      => 'America',
		'city'     => 'Guyana',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	122 => array(
		'ihg'      => 'America',
		'city'     => 'Halifax',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	123 => array(
		'ihg'      => 'America',
		'city'     => 'Havana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	124 => array(
		'ihg'      => 'America',
		'city'     => 'Hermosillo',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	125 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	126 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	127 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	128 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	129 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	130 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	131 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	132 => array(
		'ihg'      => 'America',
		'city'     => 'Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	133 => array(
		'ihg'      => 'America',
		'city'     => 'Indianapolis',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	134 => array(
		'ihg'      => 'America',
		'city'     => 'Inuvik',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	135 => array(
		'ihg'      => 'America',
		'city'     => 'Iqaluit',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	136 => array(
		'ihg'      => 'America',
		'city'     => 'Jamaica',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	137 => array(
		'ihg'      => 'America',
		'city'     => 'Jujuy',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	138 => array(
		'ihg'      => 'America',
		'city'     => 'Juneau',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	139 => array(
		'ihg'      => 'America',
		'city'     => 'Kentucky',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	140 => array(
		'ihg'      => 'America',
		'city'     => 'Kentucky',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	141 => array(
		'ihg'      => 'America',
		'city'     => 'Knox_IN',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	142 => array(
		'ihg'      => 'America',
		'city'     => 'Kralendijk',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	143 => array(
		'ihg'      => 'America',
		'city'     => 'La_Paz',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	144 => array(
		'ihg'      => 'America',
		'city'     => 'Lima',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	145 => array(
		'ihg'      => 'America',
		'city'     => 'Los_Angeles',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	146 => array(
		'ihg'      => 'America',
		'city'     => 'Louisville',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	147 => array(
		'ihg'      => 'America',
		'city'     => 'Lower_Princes',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	148 => array(
		'ihg'      => 'America',
		'city'     => 'Maceio',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	149 => array(
		'ihg'      => 'America',
		'city'     => 'Managua',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	150 => array(
		'ihg'      => 'America',
		'city'     => 'Manaus',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	151 => array(
		'ihg'      => 'America',
		'city'     => 'Marigot',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	152 => array(
		'ihg'      => 'America',
		'city'     => 'Martinique',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	153 => array(
		'ihg'      => 'America',
		'city'     => 'Matamoros',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	154 => array(
		'ihg'      => 'America',
		'city'     => 'Mazatlan',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	155 => array(
		'ihg'      => 'America',
		'city'     => 'Mendoza',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	156 => array(
		'ihg'      => 'America',
		'city'     => 'Menominee',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	157 => array(
		'ihg'      => 'America',
		'city'     => 'Merida',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	158 => array(
		'ihg'      => 'America',
		'city'     => 'Metlakatla',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	159 => array(
		'ihg'      => 'America',
		'city'     => 'Mexico_City',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	160 => array(
		'ihg'      => 'America',
		'city'     => 'Miquelon',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	161 => array(
		'ihg'      => 'America',
		'city'     => 'Moncton',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	162 => array(
		'ihg'      => 'America',
		'city'     => 'Monterrey',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	163 => array(
		'ihg'      => 'America',
		'city'     => 'Montevideo',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	164 => array(
		'ihg'      => 'America',
		'city'     => 'Montreal',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	165 => array(
		'ihg'      => 'America',
		'city'     => 'Montserrat',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	166 => array(
		'ihg'      => 'America',
		'city'     => 'Nassau',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	167 => array(
		'ihg'      => 'America',
		'city'     => 'New_York',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	168 => array(
		'ihg'      => 'America',
		'city'     => 'Nipigon',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	169 => array(
		'ihg'      => 'America',
		'city'     => 'Nome',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	170 => array(
		'ihg'      => 'America',
		'city'     => 'Noronha',
		'offset'   => -120,
		'timezone' => '-02:00',
	),
	171 => array(
		'ihg'      => 'America',
		'city'     => 'North_Dakota',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	172 => array(
		'ihg'      => 'America',
		'city'     => 'North_Dakota',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	173 => array(
		'ihg'      => 'America',
		'city'     => 'North_Dakota',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	174 => array(
		'ihg'      => 'America',
		'city'     => 'Ojinaga',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	175 => array(
		'ihg'      => 'America',
		'city'     => 'Panama',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	176 => array(
		'ihg'      => 'America',
		'city'     => 'Pangnirtung',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	177 => array(
		'ihg'      => 'America',
		'city'     => 'Paramaribo',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	178 => array(
		'ihg'      => 'America',
		'city'     => 'Phoenix',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	179 => array(
		'ihg'      => 'America',
		'city'     => 'Port-au-Prince',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	180 => array(
		'ihg'      => 'America',
		'city'     => 'Port_of_Spain',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	181 => array(
		'ihg'      => 'America',
		'city'     => 'Porto_Acre',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	182 => array(
		'ihg'      => 'America',
		'city'     => 'Porto_Velho',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	183 => array(
		'ihg'      => 'America',
		'city'     => 'Puerto_Rico',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	184 => array(
		'ihg'      => 'America',
		'city'     => 'Punta_Arenas',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	185 => array(
		'ihg'      => 'America',
		'city'     => 'Rainy_River',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	186 => array(
		'ihg'      => 'America',
		'city'     => 'Rankin_Inlet',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	187 => array(
		'ihg'      => 'America',
		'city'     => 'Recife',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	188 => array(
		'ihg'      => 'America',
		'city'     => 'Regina',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	189 => array(
		'ihg'      => 'America',
		'city'     => 'Resolute',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	190 => array(
		'ihg'      => 'America',
		'city'     => 'Rio_Branco',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	191 => array(
		'ihg'      => 'America',
		'city'     => 'Rosario',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	192 => array(
		'ihg'      => 'America',
		'city'     => 'Santa_Isabel',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	193 => array(
		'ihg'      => 'America',
		'city'     => 'Santarem',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	194 => array(
		'ihg'      => 'America',
		'city'     => 'Santiago',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	195 => array(
		'ihg'      => 'America',
		'city'     => 'Santo_Domingo',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	196 => array(
		'ihg'      => 'America',
		'city'     => 'Sao_Paulo',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	197 => array(
		'ihg'      => 'America',
		'city'     => 'Scoresbysund',
		'offset'   => -60,
		'timezone' => '-01:00',
	),
	198 => array(
		'ihg'      => 'America',
		'city'     => 'Shiprock',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	199 => array(
		'ihg'      => 'America',
		'city'     => 'Sitka',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	200 => array(
		'ihg'      => 'America',
		'city'     => 'St_Barthelemy',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	201 => array(
		'ihg'      => 'America',
		'city'     => 'St_Johns',
		'offset'   => -210,
		'timezone' => '-03:30',
	),
	202 => array(
		'ihg'      => 'America',
		'city'     => 'St_Kitts',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	203 => array(
		'ihg'      => 'America',
		'city'     => 'St_Lucia',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	204 => array(
		'ihg'      => 'America',
		'city'     => 'St_Thomas',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	205 => array(
		'ihg'      => 'America',
		'city'     => 'St_Vincent',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	206 => array(
		'ihg'      => 'America',
		'city'     => 'Swift_Current',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	207 => array(
		'ihg'      => 'America',
		'city'     => 'Tegucigalpa',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	208 => array(
		'ihg'      => 'America',
		'city'     => 'Thule',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	209 => array(
		'ihg'      => 'America',
		'city'     => 'Thunder_Bay',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	210 => array(
		'ihg'      => 'America',
		'city'     => 'Tijuana',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	211 => array(
		'ihg'      => 'America',
		'city'     => 'Toronto',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	212 => array(
		'ihg'      => 'America',
		'city'     => 'Tortola',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	213 => array(
		'ihg'      => 'America',
		'city'     => 'Vancouver',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	214 => array(
		'ihg'      => 'America',
		'city'     => 'Virgin',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	215 => array(
		'ihg'      => 'America',
		'city'     => 'Whitehorse',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	216 => array(
		'ihg'      => 'America',
		'city'     => 'Winnipeg',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	217 => array(
		'ihg'      => 'America',
		'city'     => 'Yakutat',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	218 => array(
		'ihg'      => 'America',
		'city'     => 'Yellowknife',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	219 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Casey',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	220 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Davis',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	221 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'DumontDUrville',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	222 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Macquarie',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	223 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Mawson',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	224 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'McMurdo',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	225 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Palmer',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	226 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Rothera',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	227 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'South_Pole',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	228 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Syowa',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	229 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Troll',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	230 => array(
		'ihg'      => 'Antarctica',
		'city'     => 'Vostok',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	231 => array(
		'ihg'      => 'Arctic',
		'city'     => 'Longyearbyen',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	232 => array(
		'ihg'      => 'Asia',
		'city'     => 'Aden',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	233 => array(
		'ihg'      => 'Asia',
		'city'     => 'Almaty',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	234 => array(
		'ihg'      => 'Asia',
		'city'     => 'Amman',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	235 => array(
		'ihg'      => 'Asia',
		'city'     => 'Anadyr',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	236 => array(
		'ihg'      => 'Asia',
		'city'     => 'Aqtau',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	237 => array(
		'ihg'      => 'Asia',
		'city'     => 'Aqtobe',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	238 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ashgabat',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	239 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ashkhabad',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	240 => array(
		'ihg'      => 'Asia',
		'city'     => 'Atyrau',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	241 => array(
		'ihg'      => 'Asia',
		'city'     => 'Baghdad',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	242 => array(
		'ihg'      => 'Asia',
		'city'     => 'Bahrain',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	243 => array(
		'ihg'      => 'Asia',
		'city'     => 'Baku',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	244 => array(
		'ihg'      => 'Asia',
		'city'     => 'Bangkok',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	245 => array(
		'ihg'      => 'Asia',
		'city'     => 'Barnaul',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	246 => array(
		'ihg'      => 'Asia',
		'city'     => 'Beirut',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	247 => array(
		'ihg'      => 'Asia',
		'city'     => 'Bishkek',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	248 => array(
		'ihg'      => 'Asia',
		'city'     => 'Brunei',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	249 => array(
		'ihg'      => 'Asia',
		'city'     => 'Calcutta',
		'offset'   => 330,
		'timezone' => '+05:30',
	),
	250 => array(
		'ihg'      => 'Asia',
		'city'     => 'Chita',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	251 => array(
		'ihg'      => 'Asia',
		'city'     => 'Choibalsan',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	252 => array(
		'ihg'      => 'Asia',
		'city'     => 'Chongqing',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	253 => array(
		'ihg'      => 'Asia',
		'city'     => 'Chungking',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	254 => array(
		'ihg'      => 'Asia',
		'city'     => 'Colombo',
		'offset'   => 330,
		'timezone' => '+05:30',
	),
	255 => array(
		'ihg'      => 'Asia',
		'city'     => 'Dacca',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	256 => array(
		'ihg'      => 'Asia',
		'city'     => 'Damascus',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	257 => array(
		'ihg'      => 'Asia',
		'city'     => 'Dhaka',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	258 => array(
		'ihg'      => 'Asia',
		'city'     => 'Dili',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	259 => array(
		'ihg'      => 'Asia',
		'city'     => 'Dubai',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	260 => array(
		'ihg'      => 'Asia',
		'city'     => 'Dushanbe',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	261 => array(
		'ihg'      => 'Asia',
		'city'     => 'Famagusta',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	262 => array(
		'ihg'      => 'Asia',
		'city'     => 'Gaza',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	263 => array(
		'ihg'      => 'Asia',
		'city'     => 'Harbin',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	264 => array(
		'ihg'      => 'Asia',
		'city'     => 'Hebron',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	265 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ho_Chi_Minh',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	266 => array(
		'ihg'      => 'Asia',
		'city'     => 'Hong_Kong',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	267 => array(
		'ihg'      => 'Asia',
		'city'     => 'Hovd',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	268 => array(
		'ihg'      => 'Asia',
		'city'     => 'Irkutsk',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	269 => array(
		'ihg'      => 'Asia',
		'city'     => 'Istanbul',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	270 => array(
		'ihg'      => 'Asia',
		'city'     => 'Jakarta',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	271 => array(
		'ihg'      => 'Asia',
		'city'     => 'Jayapura',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	272 => array(
		'ihg'      => 'Asia',
		'city'     => 'Jerusalem',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	273 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kabul',
		'offset'   => 270,
		'timezone' => '+04:30',
	),
	274 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kamchatka',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	275 => array(
		'ihg'      => 'Asia',
		'city'     => 'Karachi',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	276 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kashgar',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	277 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kathmandu',
		'offset'   => 345,
		'timezone' => '+05:45',
	),
	278 => array(
		'ihg'      => 'Asia',
		'city'     => 'Katmandu',
		'offset'   => 345,
		'timezone' => '+05:45',
	),
	279 => array(
		'ihg'      => 'Asia',
		'city'     => 'Khandyga',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	280 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kolkata',
		'offset'   => 330,
		'timezone' => '+05:30',
	),
	281 => array(
		'ihg'      => 'Asia',
		'city'     => 'Krasnoyarsk',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	282 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kuala_Lumpur',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	283 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kuching',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	284 => array(
		'ihg'      => 'Asia',
		'city'     => 'Kuwait',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	285 => array(
		'ihg'      => 'Asia',
		'city'     => 'Macao',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	286 => array(
		'ihg'      => 'Asia',
		'city'     => 'Macau',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	287 => array(
		'ihg'      => 'Asia',
		'city'     => 'Magadan',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	288 => array(
		'ihg'      => 'Asia',
		'city'     => 'Makassar',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	289 => array(
		'ihg'      => 'Asia',
		'city'     => 'Manila',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	290 => array(
		'ihg'      => 'Asia',
		'city'     => 'Muscat',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	291 => array(
		'ihg'      => 'Asia',
		'city'     => 'Novokuznetsk',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	292 => array(
		'ihg'      => 'Asia',
		'city'     => 'Novosibirsk',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	293 => array(
		'ihg'      => 'Asia',
		'city'     => 'Omsk',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	294 => array(
		'ihg'      => 'Asia',
		'city'     => 'Oral',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	295 => array(
		'ihg'      => 'Asia',
		'city'     => 'Phnom_Penh',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	296 => array(
		'ihg'      => 'Asia',
		'city'     => 'Pontianak',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	297 => array(
		'ihg'      => 'Asia',
		'city'     => 'Pyongyang',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	298 => array(
		'ihg'      => 'Asia',
		'city'     => 'Qatar',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	299 => array(
		'ihg'      => 'Asia',
		'city'     => 'Qyzylorda',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	300 => array(
		'ihg'      => 'Asia',
		'city'     => 'Rangoon',
		'offset'   => 390,
		'timezone' => '+06:30',
	),
	301 => array(
		'ihg'      => 'Asia',
		'city'     => 'Riyadh',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	302 => array(
		'ihg'      => 'Asia',
		'city'     => 'Saigon',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	303 => array(
		'ihg'      => 'Asia',
		'city'     => 'Sakhalin',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	304 => array(
		'ihg'      => 'Asia',
		'city'     => 'Samarkand',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	305 => array(
		'ihg'      => 'Asia',
		'city'     => 'Seoul',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	306 => array(
		'ihg'      => 'Asia',
		'city'     => 'Shanghai',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	307 => array(
		'ihg'      => 'Asia',
		'city'     => 'Singapore',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	308 => array(
		'ihg'      => 'Asia',
		'city'     => 'Srednekolymsk',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	309 => array(
		'ihg'      => 'Asia',
		'city'     => 'Taipei',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	310 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tashkent',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	311 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tbilisi',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	312 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tehran',
		'offset'   => 210,
		'timezone' => '+03:30',
	),
	313 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tel_Aviv',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	314 => array(
		'ihg'      => 'Asia',
		'city'     => 'Thimbu',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	315 => array(
		'ihg'      => 'Asia',
		'city'     => 'Thimphu',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	316 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tokyo',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	317 => array(
		'ihg'      => 'Asia',
		'city'     => 'Tomsk',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	318 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ujung_Pandang',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	319 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ulaanbaatar',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	320 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ulan_Bator',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	321 => array(
		'ihg'      => 'Asia',
		'city'     => 'Urumqi',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	322 => array(
		'ihg'      => 'Asia',
		'city'     => 'Ust-Nera',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	323 => array(
		'ihg'      => 'Asia',
		'city'     => 'Vientiane',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	324 => array(
		'ihg'      => 'Asia',
		'city'     => 'Vladivostok',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	325 => array(
		'ihg'      => 'Asia',
		'city'     => 'Yakutsk',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	326 => array(
		'ihg'      => 'Asia',
		'city'     => 'Yangon',
		'offset'   => 390,
		'timezone' => '+06:30',
	),
	327 => array(
		'ihg'      => 'Asia',
		'city'     => 'Yekaterinburg',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	328 => array(
		'ihg'      => 'Asia',
		'city'     => 'Yerevan',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	329 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Azores',
		'offset'   => -60,
		'timezone' => '-01:00',
	),
	330 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Bermuda',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	331 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Canary',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	332 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Cape_Verde',
		'offset'   => -60,
		'timezone' => '-01:00',
	),
	333 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Faeroe',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	334 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Faroe',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	335 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Jan_Mayen',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	336 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Madeira',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	337 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Reykjavik',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	338 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'South_Georgia',
		'offset'   => -120,
		'timezone' => '-02:00',
	),
	339 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'St_Helena',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	340 => array(
		'ihg'      => 'Atlantic',
		'city'     => 'Stanley',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	341 => array(
		'ihg'      => 'Australia',
		'city'     => 'ACT',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	342 => array(
		'ihg'      => 'Australia',
		'city'     => 'Adelaide',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	343 => array(
		'ihg'      => 'Australia',
		'city'     => 'Brisbane',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	344 => array(
		'ihg'      => 'Australia',
		'city'     => 'Broken_Hill',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	345 => array(
		'ihg'      => 'Australia',
		'city'     => 'Canberra',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	346 => array(
		'ihg'      => 'Australia',
		'city'     => 'Currie',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	347 => array(
		'ihg'      => 'Australia',
		'city'     => 'Darwin',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	348 => array(
		'ihg'      => 'Australia',
		'city'     => 'Eucla',
		'offset'   => 525,
		'timezone' => '+08:45',
	),
	349 => array(
		'ihg'      => 'Australia',
		'city'     => 'Hobart',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	350 => array(
		'ihg'      => 'Australia',
		'city'     => 'LHI',
		'offset'   => 630,
		'timezone' => '+10:30',
	),
	351 => array(
		'ihg'      => 'Australia',
		'city'     => 'Lindeman',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	352 => array(
		'ihg'      => 'Australia',
		'city'     => 'Lord_Howe',
		'offset'   => 630,
		'timezone' => '+10:30',
	),
	353 => array(
		'ihg'      => 'Australia',
		'city'     => 'Melbourne',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	354 => array(
		'ihg'      => 'Australia',
		'city'     => 'NSW',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	355 => array(
		'ihg'      => 'Australia',
		'city'     => 'North',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	356 => array(
		'ihg'      => 'Australia',
		'city'     => 'Perth',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	357 => array(
		'ihg'      => 'Australia',
		'city'     => 'Queensland',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	358 => array(
		'ihg'      => 'Australia',
		'city'     => 'South',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	359 => array(
		'ihg'      => 'Australia',
		'city'     => 'Sydney',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	360 => array(
		'ihg'      => 'Australia',
		'city'     => 'Tasmania',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	361 => array(
		'ihg'      => 'Australia',
		'city'     => 'Victoria',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	362 => array(
		'ihg'      => 'Australia',
		'city'     => 'West',
		'offset'   => 480,
		'timezone' => '+08:00',
	),
	363 => array(
		'ihg'      => 'Australia',
		'city'     => 'Yancowinna',
		'offset'   => 570,
		'timezone' => '+09:30',
	),
	364 => array(
		'ihg'      => 'Brazil',
		'city'     => 'Acre',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	365 => array(
		'ihg'      => 'Brazil',
		'city'     => 'DeNoronha',
		'offset'   => -120,
		'timezone' => '-02:00',
	),
	366 => array(
		'ihg'      => 'Brazil',
		'city'     => 'East',
		'offset'   => -180,
		'timezone' => '-03:00',
	),
	367 => array(
		'ihg'      => 'Brazil',
		'city'     => 'West',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	368 => array(
		'ihg'      => 'Canada',
		'city'     => 'Atlantic',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	369 => array(
		'ihg'      => 'Canada',
		'city'     => 'Central',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	370 => array(
		'ihg'      => 'Canada',
		'city'     => 'Eastern',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	371 => array(
		'ihg'      => 'Canada',
		'city'     => 'Mountain',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	372 => array(
		'ihg'      => 'Canada',
		'city'     => 'Newfoundland',
		'offset'   => -210,
		'timezone' => '-03:30',
	),
	373 => array(
		'ihg'      => 'Canada',
		'city'     => 'Pacific',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	374 => array(
		'ihg'      => 'Canada',
		'city'     => 'Saskatchewan',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	375 => array(
		'ihg'      => 'Canada',
		'city'     => 'Yukon',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	376 => array(
		'ihg'      => 'Chile',
		'city'     => 'Continental',
		'offset'   => -240,
		'timezone' => '-04:00',
	),
	377 => array(
		'ihg'      => 'Chile',
		'city'     => 'EasterIsland',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	412 => array(
		'ihg'      => 'Europe',
		'city'     => 'Amsterdam',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	413 => array(
		'ihg'      => 'Europe',
		'city'     => 'Andorra',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	414 => array(
		'ihg'      => 'Europe',
		'city'     => 'Astrakhan',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	415 => array(
		'ihg'      => 'Europe',
		'city'     => 'Athens',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	416 => array(
		'ihg'      => 'Europe',
		'city'     => 'Belfast',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	417 => array(
		'ihg'      => 'Europe',
		'city'     => 'Belgrade',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	418 => array(
		'ihg'      => 'Europe',
		'city'     => 'Berlin',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	419 => array(
		'ihg'      => 'Europe',
		'city'     => 'Bratislava',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	420 => array(
		'ihg'      => 'Europe',
		'city'     => 'Brussels',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	421 => array(
		'ihg'      => 'Europe',
		'city'     => 'Bucharest',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	422 => array(
		'ihg'      => 'Europe',
		'city'     => 'Budapest',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	423 => array(
		'ihg'      => 'Europe',
		'city'     => 'Busingen',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	424 => array(
		'ihg'      => 'Europe',
		'city'     => 'Chisinau',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	425 => array(
		'ihg'      => 'Europe',
		'city'     => 'Copenhagen',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	426 => array(
		'ihg'      => 'Europe',
		'city'     => 'Dublin',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	427 => array(
		'ihg'      => 'Europe',
		'city'     => 'Gibraltar',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	428 => array(
		'ihg'      => 'Europe',
		'city'     => 'Guernsey',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	429 => array(
		'ihg'      => 'Europe',
		'city'     => 'Helsinki',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	430 => array(
		'ihg'      => 'Europe',
		'city'     => 'Isle_of_Man',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	431 => array(
		'ihg'      => 'Europe',
		'city'     => 'Istanbul',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	432 => array(
		'ihg'      => 'Europe',
		'city'     => 'Jersey',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	433 => array(
		'ihg'      => 'Europe',
		'city'     => 'Kaliningrad',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	434 => array(
		'ihg'      => 'Europe',
		'city'     => 'Kiev',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	435 => array(
		'ihg'      => 'Europe',
		'city'     => 'Kirov',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	436 => array(
		'ihg'      => 'Europe',
		'city'     => 'Lisbon',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	437 => array(
		'ihg'      => 'Europe',
		'city'     => 'Ljubljana',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	438 => array(
		'ihg'      => 'Europe',
		'city'     => 'London',
		'offset'   => 0,
		'timezone' => '+00:00',
	),
	439 => array(
		'ihg'      => 'Europe',
		'city'     => 'Luxembourg',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	440 => array(
		'ihg'      => 'Europe',
		'city'     => 'Madrid',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	441 => array(
		'ihg'      => 'Europe',
		'city'     => 'Malta',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	442 => array(
		'ihg'      => 'Europe',
		'city'     => 'Mariehamn',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	443 => array(
		'ihg'      => 'Europe',
		'city'     => 'Minsk',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	444 => array(
		'ihg'      => 'Europe',
		'city'     => 'Monaco',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	445 => array(
		'ihg'      => 'Europe',
		'city'     => 'Moscow',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	446 => array(
		'ihg'      => 'Europe',
		'city'     => 'Nicosia',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	447 => array(
		'ihg'      => 'Europe',
		'city'     => 'Oslo',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	448 => array(
		'ihg'      => 'Europe',
		'city'     => 'Paris',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	449 => array(
		'ihg'      => 'Europe',
		'city'     => 'Podgorica',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	450 => array(
		'ihg'      => 'Europe',
		'city'     => 'Prague',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	451 => array(
		'ihg'      => 'Europe',
		'city'     => 'Riga',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	452 => array(
		'ihg'      => 'Europe',
		'city'     => 'Rome',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	453 => array(
		'ihg'      => 'Europe',
		'city'     => 'Samara',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	454 => array(
		'ihg'      => 'Europe',
		'city'     => 'San_Marino',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	455 => array(
		'ihg'      => 'Europe',
		'city'     => 'Sarajevo',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	456 => array(
		'ihg'      => 'Europe',
		'city'     => 'Saratov',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	457 => array(
		'ihg'      => 'Europe',
		'city'     => 'Simferopol',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	458 => array(
		'ihg'      => 'Europe',
		'city'     => 'Skopje',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	459 => array(
		'ihg'      => 'Europe',
		'city'     => 'Sofia',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	460 => array(
		'ihg'      => 'Europe',
		'city'     => 'Stockholm',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	461 => array(
		'ihg'      => 'Europe',
		'city'     => 'Tallinn',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	462 => array(
		'ihg'      => 'Europe',
		'city'     => 'Tirane',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	463 => array(
		'ihg'      => 'Europe',
		'city'     => 'Tiraspol',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	464 => array(
		'ihg'      => 'Europe',
		'city'     => 'Ulyanovsk',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	465 => array(
		'ihg'      => 'Europe',
		'city'     => 'Uzhgorod',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	466 => array(
		'ihg'      => 'Europe',
		'city'     => 'Vaduz',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	467 => array(
		'ihg'      => 'Europe',
		'city'     => 'Vatican',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	468 => array(
		'ihg'      => 'Europe',
		'city'     => 'Vienna',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	469 => array(
		'ihg'      => 'Europe',
		'city'     => 'Vilnius',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	470 => array(
		'ihg'      => 'Europe',
		'city'     => 'Volgograd',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	471 => array(
		'ihg'      => 'Europe',
		'city'     => 'Warsaw',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	472 => array(
		'ihg'      => 'Europe',
		'city'     => 'Zagreb',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	473 => array(
		'ihg'      => 'Europe',
		'city'     => 'Zaporozhye',
		'offset'   => 120,
		'timezone' => '+02:00',
	),
	474 => array(
		'ihg'      => 'Europe',
		'city'     => 'Zurich',
		'offset'   => 60,
		'timezone' => '+01:00',
	),
	475 => array(
		'ihg'      => 'Indian',
		'city'     => 'Antananarivo',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	476 => array(
		'ihg'      => 'Indian',
		'city'     => 'Chagos',
		'offset'   => 360,
		'timezone' => '+06:00',
	),
	477 => array(
		'ihg'      => 'Indian',
		'city'     => 'Christmas',
		'offset'   => 420,
		'timezone' => '+07:00',
	),
	478 => array(
		'ihg'      => 'Indian',
		'city'     => 'Cocos',
		'offset'   => 390,
		'timezone' => '+06:30',
	),
	479 => array(
		'ihg'      => 'Indian',
		'city'     => 'Comoro',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	480 => array(
		'ihg'      => 'Indian',
		'city'     => 'Kerguelen',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	481 => array(
		'ihg'      => 'Indian',
		'city'     => 'Mahe',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	482 => array(
		'ihg'      => 'Indian',
		'city'     => 'Maldives',
		'offset'   => 300,
		'timezone' => '+05:00',
	),
	483 => array(
		'ihg'      => 'Indian',
		'city'     => 'Mauritius',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	484 => array(
		'ihg'      => 'Indian',
		'city'     => 'Mayotte',
		'offset'   => 180,
		'timezone' => '+03:00',
	),
	485 => array(
		'ihg'      => 'Indian',
		'city'     => 'Reunion',
		'offset'   => 240,
		'timezone' => '+04:00',
	),
	486 => array(
		'ihg'      => 'Mexico',
		'city'     => 'BajaNorte',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	487 => array(
		'ihg'      => 'Mexico',
		'city'     => 'BajaSur',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	488 => array(
		'ihg'      => 'Mexico',
		'city'     => 'General',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	489 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Apia',
		'offset'   => 780,
		'timezone' => '+13:00',
	),
	490 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Auckland',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	491 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Bougainville',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	492 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Chatham',
		'offset'   => 765,
		'timezone' => '+12:45',
	),
	493 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Chuuk',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	494 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Easter',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	495 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Efate',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	496 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Enderbury',
		'offset'   => 780,
		'timezone' => '+13:00',
	),
	497 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Fakaofo',
		'offset'   => 780,
		'timezone' => '+13:00',
	),
	498 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Fiji',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	499 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Funafuti',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	500 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Galapagos',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	501 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Gambier',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	502 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Guadalcanal',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	503 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Guam',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	504 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Honolulu',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	505 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Johnston',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	506 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Kiritimati',
		'offset'   => 840,
		'timezone' => '+14:00',
	),
	507 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Kosrae',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	508 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Kwajalein',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	509 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Majuro',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	510 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Marquesas',
		'offset'   => -570,
		'timezone' => '-09:30',
	),
	511 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Midway',
		'offset'   => -660,
		'timezone' => '-11:00',
	),
	512 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Nauru',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	513 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Niue',
		'offset'   => -660,
		'timezone' => '-11:00',
	),
	514 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Norfolk',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	515 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Noumea',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	516 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Pago_Pago',
		'offset'   => -660,
		'timezone' => '-11:00',
	),
	517 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Palau',
		'offset'   => 540,
		'timezone' => '+09:00',
	),
	518 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Pitcairn',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	519 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Pohnpei',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	520 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Ponape',
		'offset'   => 660,
		'timezone' => '+11:00',
	),
	521 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Port_Moresby',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	522 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Rarotonga',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	523 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Saipan',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	524 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Samoa',
		'offset'   => -660,
		'timezone' => '-11:00',
	),
	525 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Tahiti',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	526 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Tarawa',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	527 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Tongatapu',
		'offset'   => 780,
		'timezone' => '+13:00',
	),
	528 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Truk',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	529 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Wake',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	530 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Wallis',
		'offset'   => 720,
		'timezone' => '+12:00',
	),
	531 => array(
		'ihg'      => 'Pacific',
		'city'     => 'Yap',
		'offset'   => 600,
		'timezone' => '+10:00',
	),
	532 => array(
		'ihg'      => 'US',
		'city'     => 'Alaska',
		'offset'   => -540,
		'timezone' => '-09:00',
	),
	533 => array(
		'ihg'      => 'US',
		'city'     => 'Aleutian',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	534 => array(
		'ihg'      => 'US',
		'city'     => 'Arizona',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	535 => array(
		'ihg'      => 'US',
		'city'     => 'Central',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	536 => array(
		'ihg'      => 'US',
		'city'     => 'East-Indiana',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	537 => array(
		'ihg'      => 'US',
		'city'     => 'Eastern',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	538 => array(
		'ihg'      => 'US',
		'city'     => 'Hawaii',
		'offset'   => -600,
		'timezone' => '-10:00',
	),
	539 => array(
		'ihg'      => 'US',
		'city'     => 'Indiana-Starke',
		'offset'   => -360,
		'timezone' => '-06:00',
	),
	540 => array(
		'ihg'      => 'US',
		'city'     => 'Michigan',
		'offset'   => -300,
		'timezone' => '-05:00',
	),
	541 => array(
		'ihg'      => 'US',
		'city'     => 'Mountain',
		'offset'   => -420,
		'timezone' => '-07:00',
	),
	542 => array(
		'ihg'      => 'US',
		'city'     => 'Pacific',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	543 => array(
		'ihg'      => 'US',
		'city'     => 'Pacific-New',
		'offset'   => -480,
		'timezone' => '-08:00',
	),
	544 => array(
		'ihg'      => 'US',
		'city'     => 'Samoa',
		'offset'   => -660,
		'timezone' => '-11:00',
	),
);